services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env.dev
    volumes:
      - ./:/app  # 소스 코드를 볼륨으로 마운트
      - gradle_cache:/root/.gradle  # Gradle 캐시를 볼륨으로 유지
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env.dev
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  gradle_cache:  # Gradle 캐시를 유지하기 위한 볼륨