spring:
  application:
    name: news-invest
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD} 
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false
  template:
    provider:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect

server:
  port: ${SERVER_PORT}

risk:
  score:
    threshold: 80

jwt:
  secret: 9wjkNIekKNkgEmffVBjI420dSdQPUl/QazhKfxRiWv/IX14lpWketLyI48dO2X1heNzNp5jELk2taqrk8P9Ndw==

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      cache: true