spring:
  application:
    name: news-invest
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD} 

server:
  port: ${SERVER_PORT}

jwt:
  secret: 9wjkNIekKNkgEmffVBjI420dSdQPUl/QazhKfxRiWv/IX14lpWketLyI48dO2X1heNzNp5jELk2taqrk8P9Ndw==